name: Test Generate MADs Only

on:
  push:
    branches:
      - automationPatch
  workflow_dispatch:

jobs:
  generate_mads:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        pip install tqdm

    - name: Generate MAD files from CSV
      run: |
        mkdir -p mad
        python3 csv2mad.py ArcadeDatabase_CSV/ArcadeDatabase.csv

    - name: Commit updated MAD files
      run: |
        git config --global user.name "The CI/CD Bot"
        git config --global user.email "theypsilon@gmail.com"
        git add mad/
        if git diff --cached --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update generated MAD files"
          git push
